# -*- coding: utf-8 -*-
"""chroma_vectordb.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p2MMNBBhyIOeLqCx5G33x2VrLt_KkZdu
"""



from langchain_openai import OpenAIEmbeddings
from langchain_community.vectorstores import Chroma

from langchain_core.documents import Document

doc1 = Document(
    page_content='Virat kohli is one of the most sucessful and consistent batsman in IPL History. Known for his aggressive batting style and he play very well for his team. ',
    metadata={'team':'Royal Challengers Banglore'}
)
doc2 = Document(
    page_content='Rohit Sharma is a prolific right-handed batsman and captain, known for his elegant style and ability to score big hundreds. He has led his team to multiple IPL titles.',
    metadata={'team':'Mumbai Indians'}
)

doc3 = Document(
    page_content='MS Dhoni is a legendary wicket-keeper batsman and captain, renowned for his calm demeanor, finishing abilities, and tactical brilliance. He has been a cornerstone for his team.',
    metadata={'team':'Chennai Super Kings'}
)

doc4 = Document(
    page_content='AB de Villiers, also known as Mr. 360, is famous for his unconventional shots and explosive batting. He is one of the most exciting cricketers to watch.',
    metadata={'team':'Royal Challengers Bangalore'}
)
doc5 = Document(
    page_content='Jasprit Bumrah is a world-class fast bowler, known for his unique action, Yorkers, and death bowling skills. He is a key asset for his team in crucial situations.',
    metadata={'team':'Mumbai Indians'}
)

docs = [doc1 , doc2 , doc3 , doc4, doc5]

from dotenv import load_dotenv
load_dotenv()

vector_store = Chroma(
    embedding_function=OpenAIEmbeddings(),
    persist_directory='my_chroma_db',
    collection_name='sample'
)

vector_store.add_documents(docs)

vector_store.get(include=['embeddings', 'documents', 'metadatas'])

vector_store.similarity_search(
    query='who among these are a batsman?',
    k=3
)

doc_kohli_chef = Document(
    page_content='Virat Kohli is an excellent chef, known for his culinary skills and passion for cooking. He enjoys preparing various dishes and is quite experimental in the kitchen.',
    metadata={'occupation':'chef'}
)
vector_store.update_document(document_id='f438a17c-f3c3-4dc6-96d2-1cce0c3e62a4', document=doc_kohli_chef)

vector_store.get(include=['embeddings', 'documents', 'metadatas'])

vector_store.similarity_search(
    query='who among these are a chef?',
    k=1
)

vector_store.delete(ids=['f438a17c-f3c3-4dc6-96d2-1cce0c3e62a4'])

vector_store.get(include=['embeddings', 'documents', 'metadatas'])