# -*- coding: utf-8 -*-
"""currency_conversion_tool.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R2DeJ5j2ZpqcV_eZGEbtJmy6EJ8txfmF
"""


from langchain_openai import ChatOpenAI
from langchain_core.tools import tool
from langchain_core.messages import HumanMessage
import requests

# tool create
from langchain_core.tools import InjectedToolArg
from typing import Annotated
@tool
def get_conversion_factor(base_curr : str, target_curr : str) -> float:
  '''This function fetches the currency conversion factor between base and target currency'''
  url = f'https://v6.exchangerate-api.com/v6/064199b32a6c7d911e387aa7/pair/{base_curr}/{target_curr}'
  api_key = '064199b32a6c7d911e387aa7'

  response = requests.get(url)
  return response.json()


@tool
def convert(base_value:int, conversion_rate:Annotated[float , InjectedToolArg])->float:
  '''
   given a currency conversion rate it convert this function calculate target currency value from a given base currency value

  '''
  return base_value * conversion_rate

result = get_conversion_factor.invoke({'base_curr': 'usd', 'target_curr': 'inr'})

convert.invoke({'base_value': 100 , 'conversion_rate':result['conversion_rate']})

# tool binding
llm = ChatOpenAI()
llm_with_tools = llm.bind_tools([get_conversion_factor, convert])

messages = [HumanMessage('What is conversion factor between INR and USD , and what if i convert 10 INR into USD ')]

messages

ai_messages = llm_with_tools.invoke(messages)

messages.append(ai_messages)

ai_messages.tool_calls

import json

for tool_call in ai_messages.tool_calls:
  # execute the 1st tool and get the value of conversion_rate
  if tool_call['name'] == 'get_conversion_factor':
    tool_message1 = get_conversion_factor.invoke(tool_call)

    #fetch this conversion_rate
    conversion_rate = json.loads(tool_message1.content)['conversion_rate']
    # append this into messages
    messages.append(tool_message1)

  # execute the 2nd tool and using the conversion_rate from tool1
  if tool_call['name'] == 'convert':
    tool_call['args']['conversion_rate'] = conversion_rate
    tool_message2 = convert.invoke(tool_call)
    messages.append(tool_message2)

messages

llm_with_tools.invoke(messages).content