# -*- coding: utf-8 -*-
"""tool_calling_in_langchain.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qi0VyZ3864xXcrsUaM6_WQ9rxJ6A5PHY
"""




from langchain_openai import ChatOpenAI
from langchain_core.tools import tool
from langchain_core.messages import HumanMessage
import requests

#tool create

@tool
def multiply(a: int, b:int)->int:
  ''' Given 2 numbers a and b this tool returns their product '''
  return a*b

print(multiply.invoke({'a': 5, 'b':6}))

llm = ChatOpenAI()

# LLM tool binding
llm_with_tools = llm.bind_tools([multiply])

query = HumanMessage('can you multiply 3 and 1000')

messages = [query]

messages

result = llm_with_tools.invoke(messages)

messages.append(result)

messages

tool_result = multiply.invoke(result.tool_calls[0])

messages.append(tool_result)

messages

llm_with_tools.invoke(messages).content