# -*- coding: utf-8 -*-
"""langchain8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SMZ7-X4DY441U4gcF_T0WRisK-Svwg7l

String Output Parser : Wants response in string
"""



# from langchain_openai import ChatOpenAI
# from dotenv import load_dotenv
# load_dotenv()

# from langchain_core.prompts import PromptTemplate

# template1 = PromptTemplate(
#     template = 'Write a detailed report on {topic}',
#     input_variables=['topic']
# )

# template2 = PromptTemplate(
#     template = 'Write a 5 line summary on the following text .\n {text}',
#     input_variables=['text']
# )

# prompt1 = template1.invoke({'topic':'black hole'})

# llm = ChatOpenAI(model_name="gpt-4o-mini")

# response = llm.invoke(prompt1)

# prompt2 = template2.invoke({'text':response.content})

# response1 = llm.invoke(prompt2)

# print(response1.content)

# from langchain_core.output_parsers import StrOutputParser

# parser = StrOutputParser()

# chain = template1 | llm | parser | template2 | llm | parser
# result = chain.invoke({'topic': 'black hole'})

# print(result)

# """JSONOutputParser : don't have response schema

# """

# from langchain_core.output_parsers import JsonOutputParser

# parser1 = JsonOutputParser()

# template3 = PromptTemplate(
#     template = 'Give me 5 facts about {topic} \n {format_instruction} ',
#     input_variables=['topic'],
#     partial_variables={'format_instruction':parser1.get_format_instructions()}
# )

# result = llm.invoke(prompt)
# print(result)
# final_result = parser1.parse(result.content)
# print(final_result)

# chain = template3 | llm | parser1

# result = chain.invoke({'topic':'india'})
# print(result)

# """StructuredOutputParser : Response schema

# """



# """PyDanticOutputParser : StructuredJson + Schema"""

# from langchain_core.output_parsers import PydanticOutputParser
# from pydantic import BaseModel, Field



# class Person(BaseModel):
#     name: str = Field(description="person's name")
#     age: int = Field(description="person's age")
#     city: str = Field(description="person's city")

# parser = PydanticOutputParser(pydantic_object=Person)

# template = PromptTemplate(
#     template = 'Generate the name , age and city of a fictional {place} person \n {format_instruction} ',
#     input_variables = ['place'],
#     partial_variables = {'format_instruction':parser.get_format_instructions()}
# )

# chain = template | llm | parser

# result = chain.invoke({'place':'fijian'})
# print(result)

