# -*- coding: utf-8 -*-
"""tools_in_langchain.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FhO7XZSSvU60JYGuk-lMu6OUIzdGc0pn
"""

!pip install langchain langchain-core langchain-community pydantic duckduckgo-search

"""Built-in tool - duckduckgosearch

"""

from langchain_community.tools import DuckDuckGoSearchRun
search_tool = DuckDuckGoSearchRun()

result = search_tool.invoke('top news in india today')

print(result)

print(search_tool.name)
print(search_tool.description)
print(search_tool.args)

"""Built-in tool Shell tool"""

!pip install langchain-experimental

from langchain_community.tools import ShellTool

shell_tool = ShellTool()

result = shell_tool.invoke('whoami')

print(result)

"""CUSTOM TOOL"""

from langchain_core.tools import tool

# function logic
def multiply(a,b):
  """ Multiply two numbers"""
  return a*b

# add type hints
def multiply(a: int , b: int) -> int:
   """ Multiply two numbers"""
   return a*b

# add tool decorator
@tool
def multiply(a: int , b: int) -> int:
   """ Multiply two numbers"""
   return a*b

result = multiply.invoke({'a': 3, 'b':5})
print(result)

print(multiply.name)
print(multiply.description)
print(multiply.args)

print(multiply.args_schema.model_json_schema())

"""Custom tool using structured tool and pydantic/ BaseTool"""

from langchain.tools import BaseTool
from typing import Type
from pydantic import BaseModel , Field

class MultiplyInput(BaseModel):
  a : int = Field(required = True, description='first number')
  b : int = Field(required = True, description='second number')

class MultiplyTool(BaseTool):
  name : str = "multiply"
  description : str = 'Multiply two numbers'

  args_schema : Type[BaseModel] = MultiplyInput

  def _run(self, a: int, b: int) -> int:
    return a*b

multiply_tool = MultiplyTool()

result = multiply_tool.invoke({'a': 5, 'b': 6})

result

"""Toolkits"""

from langchain_core.tools import tool

@tool
def add(a:int, b:int) -> int:
  '''Add two numbers'''
  return a+b


@tool
def multiply(a:int, b:int)-> int:
  '''Multiply two numbers'''
  return a*b

class MathToolkit:
  def get_tools(self):
    return [ add , multiply]

toolkit = MathToolkit()
tools = toolkit.get_tools()

for tool in tools:
  print(tool.name, "=>" , tool.description)